name: icarm
description: icarm App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.4.7

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_localized_locales: ^2.0.5
  http: ^1.2.2
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.0
  firebase_messaging: ^15.1.2
  firebase_core: ^3.5.0
  sqflite: ^2.3.3+1
  animation_wrappers: ^3.0.0
  video_player: ^2.9.1
  flutter_html: ^3.0.0-beta.2
  lottie: ^3.1.0
  curved_navigation_bar: ^1.0.6
  url_launcher: ^6.3.0
  go_router: ^14.2.3
  flutter_riverpod: ^2.5.1
  bot_toast: ^4.1.3
  internet_connection_checker: ^2.0.0
  flutter_svg: ^2.0.10+1
  accordion: ^2.6.0
  flutter_secure_storage: ^9.2.2
  searchable_listview: ^2.15.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.13
  flutter_html_iframe: ^3.0.0-beta.2
  flutter_rte: ^1.0.0
  file_picker: ^8.0.7
  image_picker: ^1.1.2
  sizer_pro: ^2.2.0
  loading_animation_widget: ^1.2.1
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  crop_your_image: ^1.1.0
  audio_session: ^0.1.21
  connectivity_checker: ^1.1.0
  auto_scroll_text: ^0.0.7
  cloud_firestore: ^5.4.2
  rxdart: ^0.28.0
  timeago: ^3.7.0
  flutter_bounceable: ^1.1.0
  haptic_feedback: ^0.5.1+1
  path_provider: ^2.1.4
  uuid: ^4.4.2
  flutter_cache_manager: ^3.4.1
  screen_brightness: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logoApps.png"

flutter:
  uses-material-design: true

  fonts:
    - family: sficonsets
      fonts:
        - asset: assets/icon/sficonsets.ttf

  assets:
    - assets/image/
    - assets/image/home/
    - assets/image/events/
    - assets/image/online/
    - assets/icon/
    - assets/logos/
    - assets/video/

flutter_intl:
  #se cambia a true si queremos agregar más lenguajes
  enabled: true
  main_locale: es
  class_name: S
