name: icarm
description: icarm App

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.8

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_localized_locales: ^2.0.5
  http: ^1.1.2
  global_configuration: ^2.0.0-nullsafety.1
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.7.16
  firebase_core: ^2.25.4
  sqflite: ^2.3.2
  animation_wrappers: ^3.0.0
  video_player: ^2.8.2
  chewie: ^1.7.5
  flutter_html: ^3.0.0-beta.2
  flutter_platform_alert: ^0.5.1
  lottie: ^3.1.0
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.2.5
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  bot_toast: ^4.1.3
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.10+1
  accordion: ^2.6.0
  flutter_secure_storage: ^9.0.0
  searchable_listview: ^2.10.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  flutter_html_iframe: ^3.0.0-beta.2
  flutter_rte: ^1.0.0
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  sizer_pro: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0
  device_calendar: ^4.3.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logoApps.png"

flutter:
  uses-material-design: true

  fonts:
    - family: sficonsets
      fonts:
        - asset: assets/icon/sficonsets.ttf

  assets:
    - assets/cfg/
    - assets/image/
    - assets/image/home/
    - assets/image/events/
    - assets/image/online/
    - assets/avatars/
    - assets/icon/
    - assets/logos/
    - assets/sounds/
    - assets/video/

flutter_intl:
  #se cambia a true si queremos agregar más lenguajes
  enabled: true
  main_locale: es
  class_name: S
