name: icarm
description: icarm App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  flutter_localized_locales: ^2.0.3
  http: ^0.13.3
  global_configuration: ^2.0.0-nullsafety.1
  intl: ^0.18.0
  flutter_sfsymbols: ^2.0.0
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.4.0
  convert: ^3.1.0
  flutter_keyboard_visibility: ^5.0.0
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.0.20
  cached_network_image: ^3.2.1
  firebase_messaging: ^14.6.7
  firebase_core: ^2.15.1
  sqflite: ^2.0.3+1
  get: ^4.6.5
  animation_wrappers: ^3.0.0
  video_player: ^2.2.3
  chewie: ^1.7.0
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_html: ^3.0.0-beta.2
  flutter_platform_alert: ^0.4.0
  audioplayers: ^5.1.0
  lottie: ^2.6.0
  curved_navigation_bar: ^1.0.3
  url_launcher: ^6.1.12
  go_router: ^10.1.0
  flutter_riverpod: ^2.3.7
  bot_toast: ^4.0.4
  internet_connection_checker: ^1.0.0+1
  flutter_svg: ^2.0.7
  accordion: ^2.6.0
  flutter_secure_storage: ^9.0.0
  searchable_listview: ^2.7.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logoApps.png"

flutter:

  uses-material-design: true

  fonts:
    - family: sficonsets
      fonts:
        - asset: assets/icon/sficonsets.ttf

  assets:
    - assets/cfg/
    - assets/image/
    - assets/image/home/
    - assets/image/events/
    - assets/image/online/
    - assets/avatars/
    - assets/icon/
    - assets/logos/
    - assets/sounds/
    - assets/video/

flutter_intl:
  #se cambia a true si queremos agregar más lenguajes
  enabled: true
  main_locale: es
  class_name: S
